[package]
name = "surf-render"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Minimal wgpu renderer for mx-surf"

[dependencies]
surf-core = { workspace = true }
surf-map = { workspace = true }
bytemuck = { workspace = true }
glyphon = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
surf-map = { workspace = true }
